#
# Makefile for sat-solver/bindings/ruby/tests
#

all:
	ruby loading.rb

	ruby pool.rb
	ruby repo.rb
	ruby rpmdb.rb

	ruby solvable.rb
	ruby relation.rb
	ruby repodata.rb

	ruby providers.rb

	ruby transaction.rb
	ruby covenants.rb

	ruby solver.rb
	ruby decisions.rb
	ruby problems.rb
	ruby solutions.rb
