#!/usr/bin/ruby

#require 'pathname'

puts "rdoc #{ARGV.inspect}"

home = File.dirname __FILE__

$:.unshift(home)

new_rdoc = home+"/rdoc.rb"

File.symlink("/usr/bin/rdoc", new_rdoc) unless File.symlink?(new_rdoc)

begin
  require 'parse_swig.rb'
  require 'rdoc'
ensure
  File.delete new_rdoc
end
